[project]
name = "uvbase"
version = "0.1.0"
description = "A basic image with Jupyter and jupyter-rtc-core"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter-rtc-core>=0.1.0a0",
    "jupyterlab>=4.4.2",
]
