name: lint

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: '.'

jobs:
  lint:
    name: Lint Python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install UV and Python
        uses: ./.github/actions/install-uv
        with:
          python-version: ${{ matrix.python-version }}
          working-directory: ${{ inputs.working-directory }}

      - name: Install dependencies
        run: |
          uv sync --all-extras
        working-directory: ${{ inputs.working-directory }}

      - name: Run mypy
        run: |
          uv run mypy
        working-directory: ${{ inputs.working-directory }}

      - name: Run ruff check
        run: |
          uv run ruff check
        working-directory: ${{ inputs.working-directory }}

      - name: Verify formatting
        run: |
          uv run --script $GITHUB_WORKSPACE/scripts/verify_format.py .
        working-directory: ${{ inputs.working-directory }}
        
  lint-tf:
    name: Lint Terraform templates
    runs-on: ubuntu-latest
    if: contains(inputs.working-directory, '-tf-') || inputs.working-directory == '.'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.5"

      - name: Run terraform fmt check
        run: |
          terraform fmt -check -diff -recursive "${{ inputs.working-directory }}"
